query($recipients: [String!], $token: [String!]!, $num: Int) {
  transactions(
    recipients: $recipients
    tags: [
      { name: "Exchange", values: "Verto" }
      { name: "Type", values: "Buy" }
      { name: "Token", values: $token }
    ]
    first: $num
  ) {
    edges {
      node {
        id
        block {
          timestamp
        }
        quantity {
          ar
        }
      }
    }
  }
}
