query($recipients: [String!], $cursor: String) {
  transactions(
    recipients: $recipients
    tags: [
      { name: "Exchange", values: "Verto" }
      { name: "Type", values: "Buy" }
    ]
    after: $cursor
  ) {
    pageInfo {
      hasNextPage
    }
    edges {
      cursor
      node {
        quantity {
          ar
        }
        block {
          timestamp
        }
      }
    }
  }
}
