query($owners: [String!], $recipients: [String!], $cursor: String) {
  transactions(
    owners: $owners
    recipients: $recipients
    tags: [
      { name: "Exchange", values: "Verto" }
      { name: "Type", values: "Genesis" }
    ]
    after: $cursor
  ) {
    pageInfo {
      hasNextPage
    }
    edges {
      cursor
      node {
        id
        owner {
          address
        }
      }
    }
  }
}
