query($return: [String!]!, $order: [String!]!) {
  transactions(
    tags: [
      { name: "Exchange", values: "Verto" }
      { name: "Type", values: $return }
      { name: "Order", values: $order }
    ]
    first: 1
  ) {
    edges {
      node {
        block {
          timestamp
        }
        tags {
          name
          value
        }
      }
    }
  }
}
