query($txID: [String!]!) {
  transactions(
    tags: [
      { name: "Exchange", values: "Verto" }
      { name: "Type", values: "Confirmation" }
      { name: "Swap", values: $txID }
    ]
  ) {
    edges {
      node {
        block {
          timestamp
        }
        tags {
          name
          value
        }
      }
    }
  }
}
