query($exchange: String!, $contract: [String!]!) {
  transactions(
    owners: [$exchange]
    tags: [
      { name: "Exchange", values: "Verto" }
      { name: "Type", values: "Token" }
      { name: "Contract", values: $contract }
    ]
    first: 2147483647
  ) {
    edges {
      node {
        id
      }
    }
  }
}
