query($owners: [String!], $contractSrc: [String!]!, $num: Int) {
  transactions(
    owners: $owners
    tags: [
      { name: "Exchange", values: "Verto" }
      { name: "Type", values: "PST" }
      { name: "Contract", values: $contractSrc }
    ]
    first: $num
  ) {
    edges {
      node {
        id
      }
    }
  }
}
