query($recipients: [String!], $owners: [String!], $block: Int) {
  transactions(
    recipients: $recipients
    owners: $owners
    block: { max: $block }
  ) {
    edges {
      node {
        id
        block {
          timestamp
        }
        quantity {
          ar
        }
      }
    }
  }
}
