name: review

on: [pull_request]

jobs:
  eslint:
    name: eslint diagnostics
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: eslint
        uses: reviewdog/action-eslint@v1
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          eslint_flags: --ext .ts,.tsx
